import './globals.css';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
// import TailwindIndicator from '../components/TailwindIndicator';
import TailwindIndicator from '../components/TailwindIndicator';
import TanstackProvider from '../provider/TanstackProvider';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          {children}
          <TailwindIndicator />
        </TanstackProvider>
      </body>
    </html>
  );
}
